/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: firecracker-maintainers@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartialPmem : Defines a partial pmem device structure, used to update the rate limiter for that device, after microvm start.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialPmem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "rate_limiter", skip_serializing_if = "Option::is_none")]
    pub rate_limiter: Option<Box<models::RateLimiter>>,
}

impl PartialPmem {
    /// Defines a partial pmem device structure, used to update the rate limiter for that device, after microvm start.
    pub fn new(id: String) -> PartialPmem {
        PartialPmem {
            id,
            rate_limiter: None,
        }
    }
}
