/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 1.16.0-dev
 * Contact: firecracker-maintainers@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VsockOverride : Allows for changing the backing Unix Domain Socket of a vsock device during snapshot restore.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VsockOverride {
    /// The new path for the backing Unix Domain Socket.
    #[serde(rename = "uds_path")]
    pub uds_path: String,
}

impl VsockOverride {
    /// Allows for changing the backing Unix Domain Socket of a vsock device during snapshot restore.
    pub fn new(uds_path: String) -> VsockOverride {
        VsockOverride { uds_path }
    }
}
